spring:
  application:
    name: "stock"
    version: "1.0.0"
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none